### ISSUE TITLE
Support for Eken DVR808 #8

### ISSUE THREAD

**Issue by acassis** [mandl/808MicroCam#1]
Hi Stefan,

Thank you very much for your effort creating an open source firmware 808 camera.

I tested it on Eken 808 #8 but it didn't work:

aureo sdcc # ./ISP808 blink.bin 

Read 808 Version 
Received 8 bytes: 32 00 00 05 04 00 00 00
Received 8 bytes: 00 33 20 00 00 00 00 00
Received 8 bytes: 00 00 20 01 00 00 00 00

Start Uploading the file: blink.bin 
Received 5 bytes: 00 00 00 00 00
Write 8 bytes: 00 80 04 00 2d 10 00 00

Download Code.... 
Sent 231 bytes
Control transfer failed: transfer timed out
Bulk transfer failed: transfer timed out

Download Ready....

In fact camera #8 is a different USB device (it is 5560 instead of 1528) :
Bus 002 Device 026: ID 04fc:5560 Sunplus Technology Co., Ltd

How do you did the reverse engineering to implement the ISP? I want to adapt it to camera #8.

Best Regards,

Alan

**Comment by mandl** [comment]
Hello Alan,

using the isp.exe

Take a look at

 http://chucklohr.com/808/C3/index.html#C3VideoStampRemoved

for

driver.rar

and trace the traffic with UsbSnoop

http://www.pcausa.com/Utilities/UsbSnoop/

Best regards

Stefan

2012/1/29 acassis <
reply@reply.github.com
