### ISSUE TITLE
Features of firmware

### ISSUE THREAD

**Issue by mun3** [mandl/808MicroCam#2]
Hi

Thanks a lot for the effort you've put into this.

I'm very new to all this firmware programming, so I wonder if ISP808.c actually contains all of the features of the original firmware? It doesn't seem to specify the functions of the on/off buttons etc. I'm most likely missing something though.

Thanks for the help in advance.

**Comment by mandl** [comment]
Hello mun35,

take a look at my wiki. ISP808.c is a short program for loading new
software in your cam ( e.g. my blinking led sample )

regards,

Am 4. April 2012 15:12 schrieb mun35 <
reply@reply.github.com
